server:
  port: 80

spring:
  datasource:
    url: jdbc:h2:mem:test_db
    driverClassName: org.h2.Driver
    username: root
    password: 123456
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

  h2:
    console:
      enabled: true

slowbro:
  weixin:
    gongzhonghao:
      token: yiwanzhudan
      AppID: wx864b7d20397dc4fb
      AppSecret: 36bef91473d6ff82a457c108e6ae1b7b

